# Derived from https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/docker-compose.yaml

x-clickhouse-defaults: &clickhouse-defaults
  restart: on-failure
  # addding non LTS version due to this fix https://github.com/ClickHouse/ClickHouse/commit/32caf8716352f45c1b617274c7508c86b7d1afab
  image: clickhouse/clickhouse-server:24.1.2-alpine
  tty: true
  depends_on:
    - signoz-zookeeper-1
  logging:
    options:
      max-size: 50m
      max-file: "3"
  healthcheck:
    # "clickhouse", "client", "-u ${CLICKHOUSE_USER}", "--password ${CLICKHOUSE_PASSWORD}", "-q 'SELECT 1'"
    test:
      [
        "CMD",
        "wget",
        "--spider",
        "-q",
        "0.0.0.0:8123/ping"
      ]
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

x-db-depend: &db-depend
  depends_on:
    signoz-clickhouse:
      condition: service_healthy
    # otel-collector-migrator:
    #   condition: service_completed_successfully

services:

  signoz-zookeeper-1:
    image: bitnami/zookeeper:3.7.1
    hostname: zookeeper-1
    user: root
    # ports:
    #   - "2181:2181"
    #   - "2888:2888"
    #   - "3888:3888"
    volumes:
      - ../backends/data/signoz/zookeeper-1:/bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      # - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1

  signoz-clickhouse:
    <<: *clickhouse-defaults
    hostname: clickhouse
    # ports:
    #   - "9000:9000"
    #   - "8123:8123"
    #   - "9181:9181"
    volumes:
      - ../backends/signoz/clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - ../backends/signoz/clickhouse-users.xml:/etc/clickhouse-server/users.xml
      - ../backends/signoz/custom-function.xml:/etc/clickhouse-server/custom-function.xml
      - ../backends/signoz/clickhouse-cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      # - ../backends/signoz/clickhouse-storage.xml:/etc/clickhouse-server/config.d/storage.xml
      - ../backends/data/signoz/clickhouse/:/var/lib/clickhouse/
      - ../backends/signoz/user_scripts:/var/lib/clickhouse/user_scripts/

  signoz-alertmanager:
    image: signoz/alertmanager:${ALERTMANAGER_TAG:-0.23.5}
    volumes:
      - ../backends/data/signoz/alertmanager:/data
    depends_on:
      signoz-query-service:
        condition: service_healthy
    restart: on-failure
    command:
      - --queryService.url=http://signoz-query-service:8085
      - --storage.path=/data

  # Notes for Maintainers/Contributors who will change Line Numbers of Frontend & Query-Section. Please Update Line Numbers in `../backends/signoz/scripts/commentLinesForSetup.sh` & `../backends/signoz/CONTRIBUTING.md`

  signoz-query-service:
    image: signoz/query-service:${DOCKER_TAG:-0.50.0}
    command:
      [
        "-config=/root/config/prometheus.yml"
        # "--prefer-delta=true"
      ]
    # ports:
    #   - "6060:6060"     # pprof port
    #   - "8080:8080"     # query-service port
    volumes:
      - ../backends/signoz/prometheus.yml:/root/config/prometheus.yml
      - ../backends/signoz/dashboards:/root/config/dashboards
      - ../backends/data/signoz/signoz/:/var/lib/signoz/
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - ALERTMANAGER_API_PREFIX=http://signoz-alertmanager:9093/api/
      - SIGNOZ_LOCAL_DB_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "localhost:8080/api/v1/health"
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    <<: *db-depend

  signoz-frontend:
    image: signoz/frontend:${DOCKER_TAG:-0.50.0}
    restart: on-failure
    depends_on:
      - signoz-alertmanager
      - signoz-query-service
    ports:
      - "${SIGNOZ_PORT}:3301"
    volumes:
      - ../backends/signoz/common/nginx-config.conf:/etc/nginx/conf.d/default.conf

  signoz-otel-collector-migrator:
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-0.102.2}
    command:
      - "--dsn=tcp://clickhouse:9000"
    depends_on:
      signoz-clickhouse:
        condition: service_healthy

  signoz-otel-collector:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-0.102.2}
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "--manager-config=/etc/manager-config.yaml",
        "--copy-path=/var/tmp/collector-config.yaml",
        "--feature-gates=-pkg.translator.prometheus.NormalizeName"
      ]
    user: root # required for reading docker container logs
    volumes:
      - ../backends/signoz/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ../backends/signoz/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - DOCKER_MULTI_NODE_CLUSTER=false
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    # ports:
    #   # - "1777:1777"     # pprof extension
    #   - "4317:4317" # OTLP gRPC receiver
    #   - "4318:4318" # OTLP HTTP receiver
    #   # - "8888:8888"     # OtelCollector internal metrics
    #   # - "8889:8889"     # signoz spanmetrics exposed by the agent
    #   # - "9411:9411"     # Zipkin port
    #   # - "13133:13133"   # health check extension
    #   # - "14250:14250"   # Jaeger gRPC
    #   # - "14268:14268"   # Jaeger thrift HTTP
    #   # - "55678:55678"   # OpenCensus receiver
    #   # - "55679:55679"   # zPages extension
    restart: on-failure
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
      signoz-otel-collector-migrator:
        condition: service_completed_successfully
      signoz-query-service:
        condition: service_healthy
