services:
  openobserve-main:
    image: public.ecr.aws/zinclabs/openobserve:v0.10.8
    volumes:
      - ../backends/data/openobserve/data:/data
    ports:
      - "${OPENOBSERVE_PORT}:5080"
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=${OPENOBSERVE_USER_EMAIL}
      - ZO_ROOT_USER_PASSWORD=${OPENOBSERVE_PASSWORD}
