services:
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  grafana-tempo-init:
    image: grafana/tempo:2.5.0
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ../backends/data/grafana/tempo-data:/var/tempo

  grafana-tempo:
    image: grafana/tempo:2.5.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../backends/grafana/tempo.yaml:/etc/tempo.yaml
      - ../backends/data/grafana/tempo-data:/var/tempo
    # ports:
    #   - "14268:14268"  # jaeger ingest
    #   - "3200:3200"   # tempo
    #   - "9095:9095" # tempo grpc
    #   - "4317:4317"  # otlp grpc
    #   - "4318:4318"  # otlp http
    #   - "9411:9411"   # zipkin
    depends_on:
      - grafana-tempo-init

  grafana-loki:
    image: grafana/loki:3.1.0
    # ports:
    #   - "3100:3100"
    command: -config.file=/loki.yaml
    volumes:
      - ../backends/grafana/loki.yaml:/loki.yaml

  grafana-grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ../backends/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "${GRAFANA_PORT}:3000"
